### ISSUE TITLE
Function signature rendering differences between doxygen vs sphinx+breathe

### ISSUE THREAD

**Issue by bryevdv** [breathe-doc/breathe#995]
Hi, this issue is mostly me seeking information, as someone who is quite new to Breathe. I don't know what levers can be pulled to improve the situation described below, or even where all the levers are :) 

We have some fairly complicated C++ template code (technically NVCC code in `.cu[h]` files) that used to be rendered with plain Doxygen. The generated output was nice and split parameters up on separate lines with syntax highlighting, etc. Recently things were switched to a Sphinx+Breath workflow and all the nice formatting was blown away. You can see the difference in the two cases below:

## Pure Doxygen:

<img width="754" alt="Screenshot 2024-08-30 at 13 46 18" src="https://github.com/user-attachments/assets/e587e929-6c1d-4429-93f7-4ac6fec565bb">

## Sphinx + Breathe

<img width="1024" alt="Screenshot 2024-08-30 at 13 46 55" src="https://github.com/user-attachments/assets/a94f424c-ef5d-42ed-a12b-1be25aced288">

---

My question: is there some method we can use to try to get back to more legible output like the original? Looking at the actual generated HTML in both cases, the CSS structure is quite different. It's not clear that the Sphinx+Breathe output currently encodes as much information in the the form of CSS targets as the doxygen output did. i.e. I am not sure we could just fix things with a custom stylesheet. 

It's not clear if this difference is happening due to Breathe or Sphinx or something else. Any suggestions would be very welcome!

**Comment by rileyjmurray** [comment]
I'd be interested if anyone has a solution to this. So far I've only figured out how to change rendering of parameter *descriptions* after the signature (more or less eliminating levels of indentation).

**Comment by Rouslan** [comment]
The config option you're looking for is [cpp_maximum_signature_line_length](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-cpp_maximum_signature_line_length). When set, signatures longer than _cpp_maximum_signature_line_length_ characters will have each argument on a separate line.

**Comment by rileyjmurray** [comment]
Thanks so much, @Rouslan! I didn't know that sphinx-breathe played nicely with the plain sphinx c++ formatting options. I'll defer to @bryevdv for whether it fully resolves the questions of this issue.

A quick question for you. I'm able to get formatting like the image below. It strangely shows a comma after the last argument and an extra blank line before the closing parenthesis. Do you know why that might be or up to change that?
![image](https://github.com/user-attachments/assets/aee5ddbf-2fd5-4ffa-af72-499552028490)

**Comment by Rouslan** [comment]
The formatting is beyond the control of Breathe. When Sphinx reads a reStructuredText file, it converts it into its own internal representation, then one of the output writers (such as HTML, Latex or man-page) converts the intermediate representation to the output format (there are a few extra steps in-between but those are not relevant here). Breathe works by generating this intermediate representation and handing it off to Sphinx.

I'm pretty sure the apparent blank line is due to CSS padding or margins. Each theme has its own CSS files and if you want more fine-grained control, there are configuration settings to add your own CSS files.

As for the trailing comma, that appears to be [added intentionally by the HTML writer](https://github.com/sphinx-doc/sphinx/blob/04381789db7466d56d9eb29d23d979fc16604acc/sphinx/writers/html5.py#L233). Short of asking the Sphinx maintainers for an option to control it, or creating your own "Builder" extension, there doesn't appear to be any way to omit it.

**Comment by rileyjmurray** [comment]
Gotcha. Thanks all very helpful to know. Thanks again, @Rouslan!

**Comment by bryevdv** [comment]
Thanks for the pointer @Rouslan I think this can be closed unless there is a reason you want to keep open

**Comment by Rouslan** [comment]
No, feel free to close it.
